parameters:
  - name: vcpkg_key_cache
    displayName: CACHE_VCPKG_KEY
    type: string
    default: ''
  
  - name: triplet
    displayName: triplet
    type: string

  - name: build_type
    displayName: Build Type
    type: string

  - name: vcpkg_cmake
    displayName: VCPKG_CMAKE
    type: string
    default: $(VCPKG_CMAKE)
  
  - name: cmake_args
    displayName: CMAKE_ARGS
    type: string
    default: $(CMAKE_ARGS)
  
  ## TODO merge with cmake_args
  - name: cmake_ignore_path
    displayName: CMAKE_IGNORE_PATH
    type: string
    default: ''

  ## TODO: can be extracted from triplet?
  - name: arch
    displayName: arch
    type: string
    default: ''

  - name: test
    displayName: Run Test?
    type: boolean
    default: true
 
  - name: install
    displayName: Run install?
    type: boolean
    default: true
 
  - name: package
    displayName: Run pacakge?
    type: boolean
    default: true

steps:
- template: 'vcpkg-cache-step.yml'
  parameters:
    vcpkg_key_cache: ${{ parameters.vcpkg_key_cache }}
    triplet: ${{ parameters.triplet }}
- template: 'cmake-gen-build-steps.yml'
  parameters:
    build_type: ${{ parameters.build_type }}
    triplet: ${{ parameters.triplet }}
    vcpkg_cmake: ${{ parameters.vcpkg_cmake }}
    cmake_args: ${{ parameters.cmake_args }}
    cmake_ignore_path: ${{ parameters.cmake_ignore_path }}
    arch: ${{ parameters.arch }}
    #build_wrapper:
- ${{ if eq(parameters.test, true) }}:
  - template: 'cmake-test-steps.yml'
    parameters:
      build_type: ${{ parameters.build_type }}

- ${{ if eq(parameters.install, true) }}:
  - script: cmake --build . --target install
    displayName: cmake --target install
    workingDirectory: build

- ${{ if eq(parameters.package, true) }}:
  - script: cmake --build . --target package
    displayName: cmake --target package
    workingDirectory: build
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/build'
      contents: '*.zip'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 'Raffaello'
      repositoryName: '$(Build.Repository.Name)' 
      action: 'edit' #'create' # Options: create, edit, delete
      target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
      tagSource: 'auto' # Required when action == Create# Options: auto, manual
      #tagPattern: # Optional
      tag: $(Build.SourceBranchName)
      title: $(Build.SourceBranchName)
      #releaseNotesSource: 'file' # Optional. Options: file, input
      #releaseNotesFile: # Optional
      #releaseNotes: # Optional
      assets: '$(Build.ArtifactStagingDirectory)/*.zip' # Optional
      assetUploadMode: 'replace' #'delete' # Optional. Options: delete, replace
      isDraft: true # Optional
      #isPreRelease: false # Optional
      addChangeLog: true # Optional
      compareWith: 'lastFullRelease' # Required when addChangeLog == True. Options: lastFullRelease, lastRelease, lastReleaseByTag
      #releaseTag: # Required when compareWith == LastReleaseByTag
    condition: contains(variables['Build.SourceBranch'], 'refs/tags/')
