### not used

parameters:
  - name: imageName
    displayName: Image
    type: string
    #default: 
    #values:
    #- 'ubuntu-16.04'
    #- 'macOS-10.15'
    #- 'windows-2019'
  
  - name: triplet
    displayName: triplet
    type: string
  
  - name: arch
    displayName: arch
    type: string
    default: ''
    
jobs:
- job: vcpkg
  pool:
    vmImage: ${{ parameters.imageName }}
  steps:
  - checkout: none
  - task: Cache@2
    inputs:
      key: '$(CACHE_VCPKG_KEY) | $(TRIPLET)'
      path: "vcpkg"
      cacheHitVar: CACHE_RESTORED
  - bash: test -d vcpkg || git clone https://github.com/Microsoft/vcpkg.git
    displayName: clone vcpkg
  - bash: |
      ./bootstrap-vcpkg.sh 
      ./vcpkg install sdl2 sdl2-image gtest --triplet ${{ parameters.triplet }}
      rm -rf buildtrees/* docs/* downloads/* packages/*
    workingDirectory: vcpkg
    displayName: vcpkg unix
    condition: and(ne(variables['Agent.OS'], 'Windows_NT'), ne(variables.CACHE_RESTORED, 'true'))
  - script: |
      call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ parameters.arch}}.bat"
      call bootstrap-vcpkg.bat 
      vcpkg.exe install sdl2 sdl2-image gtest --triplet ${{ parameters.triplet }}
      del /Q /S buildtrees docs downloads packages > NUL
    workingDirectory: vcpkg
    displayName: vcpkg win
    condition: and(eq(variables['Agent.OS'], 'Windows_NT'), ne(variables.CACHE_RESTORED, 'true'))
