parameters:
  - name: vcpkg_key_cache
    displayName: CACHE_VCPKG_KEY
    type: string
    default: ''
    
  - name: packages
    displayName: packages
    type: string
    default: 'sdl2 sdl2-image gtest'

  - name: triplet
    displayName: triplet
    type: string
  
  - name: arch
    displayName: arch
    type: string
    default: ''
    
variables:
  REMOVABLES: buildtrees docs downloads packages .git .github ports toolsrc
## TODO: use resource git hub instead of clone, try

steps:
- checkout: none
- template: 'vcpkg-cache-step.yml'
  parameters:
    vcpkg_key_cache: ${{ parameters.vcpkg_key_cache }}
    triplet: ${{ parameters.triplet }}
- bash: test -d vcpkg || git clone https://github.com/Microsoft/vcpkg.git
  displayName: clone vcpkg
- script: echo "installing packages ${{ parameters.packages }}"
  displayName: packages
- bash: |
    ./bootstrap-vcpkg.sh 
    ./vcpkg install ${{ parameters.packages }} --triplet ${{ parameters.triplet }}
    rm -rf $(REMOVABLES)
  workingDirectory: vcpkg
  displayName: vcpkg unix
  condition: and(ne(variables['Agent.OS'], 'Windows_NT'), ne(variables.CACHE_RESTORED, 'true'))
- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ parameters.arch}}.bat"
    call bootstrap-vcpkg.bat 
    vcpkg.exe install ${{ parameters.packages }} --triplet ${{ parameters.triplet }}
    del /Q /S $(REMOVABLES) > NUL
  workingDirectory: vcpkg
  displayName: vcpkg win
  condition: and(eq(variables['Agent.OS'], 'Windows_NT'), ne(variables.CACHE_RESTORED, 'true'))
