parameters:
  - name: vcpkg_key_cache
    displayName: CACHE_VCPKG_KEY
    type: string
    default: ''
    
  - name: packages
    displayName: packages
    type: string
    default: 'sdl2 sdl2-image gtest'

  - name: triplet
    displayName: triplet
    type: string
  
  - name: arch
    displayName: arch
    type: string
    default: ''
    #values:
    #  - 32
    #  - 64
    
steps:
- checkout: none
- task: Cache@2
  inputs:
    key: '${{ parameters.vcpkg_key_cache }} | ${{ parameters.triplet }}'
    path: "vcpkg"
    cacheHitVar: CACHE_RESTORED
- bash: test -d vcpkg || git clone https://github.com/Microsoft/vcpkg.git
  displayName: clone vcpkg
- script: echo "installing packages ${{ parameters.packages }}"
  displayName: packages
- bash: |
    ./bootstrap-vcpkg.sh 
    ./vcpkg install ${{ parameters.packages }} --triplet ${{ parameters.triplet }}
    rm -rf buildtrees/* docs/* downloads/* packages/*
  workingDirectory: vcpkg
  displayName: vcpkg unix
  condition: and(ne(variables['Agent.OS'], 'Windows_NT'), ne(variables.CACHE_RESTORED, 'true'))
- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ parameters.arch}}.bat"
    call bootstrap-vcpkg.bat 
    vcpkg.exe install ${{ parameters.packages }} --triplet ${{ parameters.triplet }}
    del /Q /S buildtrees docs downloads packages > NUL
  workingDirectory: vcpkg
  displayName: vcpkg win
  condition: and(eq(variables['Agent.OS'], 'Windows_NT'), ne(variables.CACHE_RESTORED, 'true'))
