parameters:
  - name: vcpkg_key_cache
    displayName: CACHE_VCPKG_KEY
    type: string
    default: ''
    
  - name: packages
    displayName: packages
    type: string
    default: 'sdl2 sdl2-image gtest'

  - name: triplet
    displayName: triplet
    type: string
  
  - name: arch
    displayName: arch
    type: string
    default: ''

steps:
- task: Cache@2
  inputs:
    key: '${{ parameters.vcpkg_key_cache }} | ${{ parameters.triplet }}'
    path: "vcpkg"
    cacheHitVar: CACHE_RESTORED
- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars%ARCH%.bat"
    mkdir build && cd build
    cmake -DCMAKE_IGNORE_PATH="%CMAKE_IGNORE_PATH%" -G"Ninja" -DCMAKE_BUILD_TYPE=$(BuildType) -DCMAKE_TOOLCHAIN_FILE=%VCPKG_CMAKE% %CMAKE_ARGS% ..
  displayName: 'CMake generator'
- task: Cache@2
  inputs:
    key: 'build-wrapper | "$(Agent.OS)"'
    path: "build/build-wrapper-win-x86"
    cacheHitVar: CACHED_WRAPPER
  displayName: "(cache) build-wrapper"
- bash: |
    curl $SONAR_CLOUD_WRAPPER_URL --output build-wrapper.zip
    unzip build-wrapper.zip
  workingDirectory: build
  displayName: build-wrapper
  condition: ne(variables.CACHED_WRAPPER, 'true')
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarCloud'
    organization: 'raffaello-github'
    scannerMode: 'CLI'
    configMode: 'file'        
  displayName: Prepare sonarCloud
- script: |
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars%ARCH%.bat"
    build-wrapper-win-x86\build-wrapper-win-x86-64.exe --out-dir bw-output cmake --build .
  workingDirectory: build
  displayName: sonarCloud build
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '600'
