# trigger:
#   branches:
#     include:
#     - master
#   paths:
#     exclude:
#     #- .gitignore
#     - .github/*
#     - README.md
#     - appveyor.yml
#   tags:
#     include:
#     - '*'

# pr:
#   branches:
#     include:
#     - master
#   paths:
#     exclude:
#     #- .gitignore
#     - .github/*
#     - README.md
#     - appveyor.yml
#     - LICENSE

resources:
  pipelines:
  - pipeline: windows-ci   # Name of the pipeline resource
    source: Raffaello.sdl2-vga-terminal.Windows # Name of the triggering pipeline
    # trigger: 
    #   branches:
    #   - releases/*
    #   - master

variables:
  - template: variables.yml

stages:
- stage: Dep
  jobs:
    - job: vcpkg
      strategy:
        matrix:
        #   Linux:
        #     imageName: ${{ variables.linux_image }}
        #     TRIPLET: x64-linux
        #   MacOS:
        #     imageName: ${{ variables.mac_image }}
        #     TRIPLET: x64-osx
        #   Win 32 bits:
        #     imageName: ${{ variables.windows_image }}
        #     TRIPLET: x86-windows
        #     ARCH: 32
          Win 64 bits:
            imageName: ${{ variables.windows_image }}
            TRIPLET: x64-windows
            ARCH: 64
      pool:
        vmImage: $(imageName)
      steps:
      - template: templates/dep-vcpkg-steps.yml
        parameters:
          vcpkg_key_cache: $(CACHE_VCPKG_KEY)
          triplet: $(TRIPLET)
          arch: $(ARCH)

- stage: Analyzer
  jobs: 
    - template: 'templates/sonarcloud-job.yml'
      parameters:
        imageName: ${{ variables.windows_image }}
        jobName: SonarCloud_win
        jobDisplayName: SonarCloud (WIN)
        vcpkg_key_cache: $(CACHE_VCPKG_KEY)
        triplet: x64-windows
        arch: 64
        build_type: Debug
        sonar_wrapper_url: 'https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip'
        build_wrapper: 'build-wrapper-win-x86\build-wrapper-win-x86-64.exe'
        build_wrapper_path: build/build-wrapper-win-x86
        cmake_ignore_path: $(CMAKE_IGNORE_PATH_WIN)
