trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    #- .gitignore
    - .github/*
    - README.md
    - appveyor.yml
    - LICENSE
    - lgtm.yml

  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    #- .gitignore
    - .github/*
    - README.md
    - appveyor.yml
    - LICENSE

variables:
  - template: variables/global.yml
  - template: variables/images.yml
  - template: variables/build_switches.yml

stages:
- stage: Dep
  jobs:
    - job: vcpkg
      strategy:
        matrix:
          osx:
            imageName: ${{ variables.mac_image }}
            TRIPLET: x64-osx
      pool:
        vmImage: $(imageName)
      steps:
      - template: templates/dep-vcpkg-steps.yml
        parameters:
          vcpkg_key_cache: $(CACHE_VCPKG_KEY)
          triplet: $(TRIPLET)
          arch: $(ARCH)


- stage: Analyzer
  variables:
    BUILD_EXAMPLES: OFF
    BUILD_SHARED_LIBS: ON
    ENABLE_CODE_COVERAGE: ON    
    HAVE_PRECISE_TIMER: OFF
  jobs: 
    - template: 'templates/sonarcloud-job.yml'
      parameters:
        imageName: ${{ variables.mac_image }}
        jobName: SonarCloud_macos
        jobDisplayName: SonarCloud (macOS)
        vcpkg_key_cache: $(CACHE_VCPKG_KEY)
        triplet: x64-osx
        build_type: Debug
        sonar_wrapper_url: 'https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip'
        build_wrapper: 'build-wrapper-macosx-x86/build-wrapper-macosx-x86'
        build_wrapper_path: build/build-wrapper-macosx-x86

    ### the cmake-gen-build-steps should be geneneralized to accept different
    ### arguments from the build-wrapper, and the build wrapper in this case
    ### is scan-build tool, at the moment make it working, 2nd iteration
    ### generalize that themplate.
    - job: cpplint
      pool:
        vmImage: ${{ variables.mac_image }}
      steps:
        - script: pip install cpplint
          displayName: install cpplint
        - script: chmod +x cpplint.sh && ./cpplint.sh 2> cpplint.log || echo "-==*** ignoring linting warnings ***==-"
          displayName: cpplint
          continueOnError: true
        # Publish (upload) a file or directory as a named artifact for the current run
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: cpplint.log
            artifactName: 'cpplint.log'
        - script: cat cpplint.log
          displayName: cpplint result

