trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    #- .gitignore
    - .github/*
    - README.md
    - appveyor.yml
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    #- .gitignore
    - .github/*
    - README.md
    - appveyor.yml
    - LICENSE

variables:
  - template: variables/global.yml
  - template: variables/images.yml
  - template: variables/build_switches.yml

stages:
- stage: Dep
  jobs:
    - job: vcpkg
      pool:
        vmImage: ${{ variables.linux_image }}
      steps:
      - template: templates/dep-vcpkg-steps.yml
        parameters:
          vcpkg_key_cache: $(CACHE_VCPKG_KEY)
          triplet: x64-linux

- stage: CI
  jobs:
    - job: Linux
      strategy:
        matrix:
          GCC Debug:
            CONFIGURATION: Debug
          GCC Release:
            CONFIGURATION: Release
      pool:
        vmImage: ${{ variables.linux_image }}
      steps:
      - template: 'templates/ci-steps.yml'
        parameters:
          vcpkg_key_cache: $(CACHE_VCPKG_KEY)
          triplet: x64-linux
          build_type: $(CONFIGURATION)
          test: false
          install: false
